[versions]

kotlin = "2.0.20"
androidGradlePlugin = "8.6.1"
firebaseCrashlytics = "19.0.3"
anrWatchDog = "1.4.0"
kermit = "2.0.4"

[libraries]
# COMMON
common-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
common-kermitCrashlytics = { module = "co.touchlab:kermit-crashlytics", version.ref = "kermit" }

# ANDROID
android-firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "firebaseCrashlytics" }
android-anrWatchDog = { module = "com.github.anrwatchdog:anrwatchdog", version.ref = "anrWatchDog" }

[plugins]

kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
